# Generated by Django 3.0.6 on 2020-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_edu_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('edudetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ESkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('workdetail', models.TextField()),
            ],
        ),
    ]
