# Generated by Django 3.0.6 on 2020-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_acaoutput_pracoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=1000)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ECSoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=1000)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
    ]
